### ISSUE TITLE
Changed header to "What we do"

### ISSUE THREAD

**Issue by little-wow** [creativecommons/new-creativecommons.org#7]
Changed header language to "What we do" and "Blog," which creates potential issue with overlap in text and image.
<img width="1270" alt="screen shot 2016-06-17 at 4 29 20 pm" src="https://cloud.githubusercontent.com/assets/7093838/16163688/b8eeb25e-34a8-11e6-947e-331cd065cf4c.png">

**Comment by mattl** [comment]
Any more changes like this coming? We have to make static versions of this template in a variety of other places, outside of WordPress.

**Comment by ageeroms** [comment]
Hello Matt,

I don't have anymore open tickets. The last change we made on staging was
re the capitalization of the items listed in sub-navigation. The CSS was
capitalizing the first letter of every item in In This Section, which was
inconsistent with the style Ryan requested. That is likely not effect your
FAQ/Chooser since you omit the sidebar entirely in both cases. Please let
me know if you do want the CSS for the static site updated per that change,
but otherwise, I think you should be good to go.

Anna

On Fri, Jun 17, 2016 at 2:47 PM, Matt Lee <notifications@github.com> wrote:

> Any more changes like this coming? We have to make static versions of this
> template in a variety of other places, outside of WordPress.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/creativecommons/new-creativecommons.org/issues/7#issuecomment-226889492>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGXZDsE6b-dWIhboDTjeNFH-eF99-tWrks5qMxYFgaJpZM4I4tJe>
> .
>



-- 
Anna Geeroms | Business Analyst
Affinity Bridge

http://affinitybridge.com
T. 604.569.0510 | E. anna@affinitybridge.com

710 - 207 W. Hastings St.
Vancouver, BC
V6B 1H7

**Comment by little-wow** [comment]
@ageeroms what about the image issue we talked about that I flagged in this ticket? Are you going to address that with your designer? If not, I can close the ticket.

**Comment by ageeroms** [comment]
Hey @mattl , apologies, I missed two things that impact the static template:

As Jennie mentioned, she adjusted the top level navigation items to say What we do & Blog, instead of About CC & News . So far this doesn't look to me to effect the responsive behaviour. So just needs text/link updates.

Likewise the footer has a typo--two numbers reversed in the phone. 

I'll ask our dev to make those updates and send updated files asap.

Thanks,
Anna

**Comment by ageeroms** [comment]
@mattl @robmyers our dev is going to provide updated HTML/CSS for static sites per previous described issues. Also, the donate button in the header had a tiny blip on the corner and he updated the CC heart to be higher resolution, which you can see on stage. I'll provide files asap.
